### PR TITLE
Logic to allow other valid recipe formats

### PR DESCRIPTION
**Pull request by anythingapplied**
Both ingredients and results can take either format:
{"iron-plate", 1} or
{type="item", name="iron-plate", amount=1}

Also, a valid, but rarely used recipe format is to
specify either .normal or .expensive, but not the other.

### CODE REVIEW

**Comment by Yousei9** [comment]
**SelectItemsByRecipeInput**
Nice catch, I'll add support for that in the next release.

**SelectItemsByRecipeResult**
What would be the point of expensive recipes having a different result from normal recipes?
Can you even set expensive.results to different values from normal.results?

**SelectItemByEntity**
minable has a different format from recipes.
`minable = {mining_time = n, result = "item_name"}`
I've never seen the short format your change accommodates.

**Comment by anythingapplied** [comment]
I wasn't think about results being different, but rather this was aimed at recipes where recipe.normal = nil or false but recipe.expensive is specified.  If only one of the two are specified, it'll use the one  normal/expensive version for both. More information [here](https://wiki.factorio.com/Prototype/Recipe#Modified_so_that_the_expensive_recipe_is_always_used.2C_even_in_normal_mode). My code doesn't really account for a difference, just .normal not being specified. I'm not sure if the game rejects a difference.

As far as your other questions, I'd have to some testing. The format I posted I believe would come into play if you used .results=. I think it was the byEntity that might have caused the game crash (.name was nil and can't be used as a table ref) that got me looking at your code. I have a group of 125 mods I test my mod with and when someone reported an issue between my mod and your mod I added it to the pack, but found your mod had a conflict with one of the other 125 mods.

When I get back to my computer I can do some digging into your questions and also provide the initial mod that had the format that caused your mod to crash.

**Comment by Yousei9** [comment]
I've added and expanded your fixes for SelectItemsByRecipeInput and SelectItemsByRecipeResult locally. So far it worked in my test environment. 
I have no idea how to incorporate my changes into your pull on github.

**Comment by anythingapplied** [comment]
I found the issue that I original set out to fix because of an issue with your SelectItemByEntity function when trying to use [Pyanodons Coal Processing](https://mods.factorio.com/mod/pycoalprocessing) I get the following error:

` __ReStack__/data-final-fixes.lua:11: __ReStack__/modules/lib.lua:12: table index is nil`

because pyanodon has a perfectly valid .minable of:

```
fluid_amount = 50,
  hardness = 1.5,
  mining_time = 3,
  required_fluid = "syngas",
  results = { { "raw-borax", 1 } }

```

Which is why I implemented changes in that function as well.

I'm pretty new to pull requests too (this is my first one ever), but there should be ways to modify this before incorporating it.  Like [here](https://github.com/castleproject/Windsor/pull/394) for example you can see there are requested changes where the pull request is modified.

**Comment by Yousei9** [comment]
Please test if my changes work with your mods.

**Comment by anythingapplied** [comment]
When I tried your code it worked perfectly.  My only pieces of feedback are related to hypothetical issues that I've never actually seen come up, so they are more if you want to edge-case proof your code:

First, if a recipe has .normal or .expensive then .result/.results doesn't get used at all, so you may be adding extra recipes excluded by the game.

Secondly, instead of checking for nil values, I've actually started doing type(recipe) == 'table'.  This both checks for nil (type(nil) is nil, and so wouldn't be 'table') and at the same time makes sure that it is an actual table so that your mod doesn't error out when you check if recipe.name is nil.  But again, I've never seen this hypothetical issue come up and it would likely crash the game, but at least it wouldn't be your mod crashing the game as a result of someone else's bad recipe.

**Comment by Yousei9** [comment]
Good to hear it works.

You may have misread the code a bit there.
The previous version would only the first match for results, normal.results, expensive.results. the version i updated adds every item it finds in all 3 to the restack table like it does with ingredients.

A very plausible glitch happens with items showing up in multiple recipes. As long as I'm careful about the order in which I add items this shouldn't become a problem, but it's always possible I didn't account for mods returning copper ore when mining an assembler or something bizarre like that.

As you said Factorio will crash instantly if a mod uses invalid formatting or types long before any other mod sees the mess, making those checks redundant.

**Comment by anythingapplied** [comment]
> As you said Factorio will crash instantly

It doesn't crash instantly.  It waits to validate the recipes until all mods are loaded.  So with an bad mod it might never get to recipe validation if your mod crashes on it first, which would make your mod look responsible. But the crash would happen eventually anyway, which is why it still may not be a big deal for you anyway.

**Pull request merged**
